// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLxAPJfGjV-wwDHmAQrvIpExoSvPyjbo',
    appId: '1:581165450744:web:01bf60175466f805fbc20d',
    messagingSenderId: '581165450744',
    projectId: 'flutter-1f2ab',
    authDomain: 'flutter-1f2ab.firebaseapp.com',
    storageBucket: 'flutter-1f2ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6P7ueELkodGzpWuidt8ZvSADdK0ENbxk',
    appId: '1:581165450744:android:d4dbd57ad1a25603fbc20d',
    messagingSenderId: '581165450744',
    projectId: 'flutter-1f2ab',
    storageBucket: 'flutter-1f2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwdaUiy_XFIpbvJFR0Kt2QdVQ-YSq49iY',
    appId: '1:581165450744:ios:1008a7371620f410fbc20d',
    messagingSenderId: '581165450744',
    projectId: 'flutter-1f2ab',
    storageBucket: 'flutter-1f2ab.firebasestorage.app',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwdaUiy_XFIpbvJFR0Kt2QdVQ-YSq49iY',
    appId: '1:581165450744:ios:1008a7371620f410fbc20d',
    messagingSenderId: '581165450744',
    projectId: 'flutter-1f2ab',
    storageBucket: 'flutter-1f2ab.firebasestorage.app',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYLxAPJfGjV-wwDHmAQrvIpExoSvPyjbo',
    appId: '1:581165450744:web:f9828059c6f72321fbc20d',
    messagingSenderId: '581165450744',
    projectId: 'flutter-1f2ab',
    authDomain: 'flutter-1f2ab.firebaseapp.com',
    storageBucket: 'flutter-1f2ab.firebasestorage.app',
  );
}
